name: 'Mobsf Scan'
description: 'Mobsf Scan for BYCN Project'
inputs:
  MOBSF_URL:  # Mobsf Server
    description: 'Url for mobsf Server'
    required: true
    default: 'localhost:8000'
  AUTH: # authentication
    description: 'base64 to authentication'
    required: true
  MOBSF_API_KEY:  # Mobsf API Key
    description: 'Key for mobsf Server'
    required: true
    default: 'XXX'
  INPUT_FILE_NAME:  # Mobsf Server
    description: 'Input file name'
    required: true
    default: app-release.apk
  OUTPUT_FILE_NAME:  # Mobsf Server
    description: 'Output file name'
    required: true
    default: 'mobsf-report'
  SCAN_TYPE:  # Mobsf Server
    description: 'Scan type for mobsf Server'
    required: true
    default: 'apk'
  
  

runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/scan.sh
      shell: bash
      env: 
        MOBSF_URL: ${{ inputs.MOBSF_URL }}
        MOBSF_API_KEY: ${{ inputs.MOBSF_API_KEY }}
        INPUT_FILE_NAME: ${{ inputs.INPUT_FILE_NAME }}
        OUTPUT_FILE_NAME: ${{ inputs.OUTPUT_FILE_NAME }}
        SCAN_TYPE: ${{ inputs.SCAN_TYPE }}
        AUTH: ${{ AUTH }}
